#program for demonstarting the functionality of arithmetic operators
#Arithmetic Operators
a=int(input("enter value of a:"))
b=int(input("enter value of b:"))
print("*"*60)
print("\tArithmetic Operators Results")
print("*"*60)
print("\t\tsum({},{})={}".format(a,b,a+b))
print("\t\tsub({},{})={}".format(a,b,a-b))
print("\t\tmul({},{})={}".format(a,b,a*b))
print("\t\tdiv({},{})={}".format(a,b,a/b))
print("\t\tfloordiv({},{})={}".format(a,b,a//b))
print("\t\tmoddiv({},{})={}".format(a,b,a%b))
print("\t\texp({},{})={}".format(a,b,a**b))
print("*"*60)